services:
  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks: [elastic]

  kibana:
    image: kibana:8.5.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_REQUESTTIMEOUT=120000
    ports:
      - "5601:5601"
    networks: [elastic]
    depends_on: [elasticsearch]

  filebeat:
    image: elastic/filebeat:8.11.0
    container_name: filebeat
    user: "0"                       # чтобы точно было право читать файлы
    environment:
      - STRICT_PERMS=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro              # <-- монтируем папку с 1.log
      # Если не читаем логи контейнеров — эти два монтирования можно убрать:
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # - /var/run/docker.sock:/var/run/docker.sock
    networks: [elastic]
    depends_on: [elasticsearch]
    restart: unless-stopped

  nginx-test:
    image: nginx:alpine
    container_name: nginx-test
    ports:
      - "8080:80"
    networks: [elastic]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx

volumes:
  es_data:
    driver: local

networks:
  elastic:
    driver: bridge
